# Generated by Django 5.2.4 on 2025-07-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strike_price', models.FloatField()),
                ('expiry_date', models.CharField(max_length=50)),
                ('call_oi', models.BigIntegerField()),
                ('put_oi', models.BigIntegerField()),
                ('call_ltp', models.FloatField()),
                ('put_ltp', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
