# Generated by Django 5.2.4 on 2025-07-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='NIFTY', max_length=10)),
                ('option_type', models.CharField(choices=[('CE', 'Call'), ('PE', 'Put')], max_length=2)),
                ('strike_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiry_date', models.DateField()),
                ('identifier', models.CharField(max_length=50, unique=True)),
                ('last_price', models.FloatField()),
                ('change', models.FloatField()),
                ('p_change', models.FloatField()),
                ('total_traded_volume', models.BigIntegerField()),
                ('open_interest', models.BigIntegerField()),
                ('change_in_oi', models.BigIntegerField()),
                ('p_change_in_oi', models.FloatField()),
                ('bid_qty', models.BigIntegerField()),
                ('bid_price', models.FloatField()),
                ('ask_qty', models.BigIntegerField()),
                ('ask_price', models.FloatField()),
                ('total_buy_qty', models.BigIntegerField()),
                ('total_sell_qty', models.BigIntegerField()),
                ('implied_volatility', models.FloatField()),
                ('underlying_value', models.FloatField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='OptionData',
        ),
    ]
