# Generated by Django 5.2.4 on 2025-07-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0002_optioncontract_delete_optiondata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optioncontract',
            name='identifier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
